#! python


def build(ctx):

    for model in '1', '2','3','4':

        ctx(
            features='run_py_script',
            source='plot_beta_hat.py',
            deps=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'simulation_{}.pickle'.format(model))
            ],
            target=[
                ctx.path_to(ctx, 'OUT_FIGURES', 'beta_hat_ichimura_{}.png'.format(model)),
                ctx.path_to(ctx, 'OUT_FIGURES', 'beta_hat_KS_{}.png'.format(model)),
                ctx.path_to(ctx, 'OUT_FIGURES', 'beta_hat_log_{}.png'.format(model))
            ],
            append=model,
            name='plot_beta_hat_{}'.format(model)
        )


    ctx(
        features='run_py_script',
        source='table_beta_hat.py',
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'simulation_3.pickle'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'simulation_4.pickle'),
            ctx.path_to(ctx, 'IN_MODEL_SPECS', 'model_3.json')
            ],
        target=[
            ctx.path_to(ctx, 'OUT_TABLES', 'table_bias.tex'),
            ],
        append=model,
        name='table_bias'
    )

    ctx(
    features='run_py_script',
    source='table_consistency.py',
    deps=[
        ctx.path_to(ctx, 'OUT_ANALYSIS', 'simulation_1.pickle'),
        ctx.path_to(ctx, 'OUT_ANALYSIS', 'simulation_2.pickle'),
        ctx.path_to(ctx, 'OUT_ANALYSIS', 'simulation_3.pickle'),
        ctx.path_to(ctx, 'IN_MODEL_SPECS', 'model_3.json')
        ],
    target=[
        ctx.path_to(ctx, 'OUT_TABLES', 'table_consistency.tex'),
        ],
    append=model,
    name='table_consistency'
)

    ctx(
    features='run_py_script',
    source='table_empirical.py',
    deps=[
        ctx.path_to(ctx, 'OUT_EMPIRICAL', 'empirical.pickle'),
        ],
    target=[
        ctx.path_to(ctx, 'OUT_TABLES', 'table_empirical.tex'),
        ],
    append=model,
    name='table_empirical'
)

