ichimura_1=read.csv("ichimura_1.csv",header=TRUE)
ichimura_2=read.csv("ichimura_2.csv",header=TRUE)
ichimura_3=read.csv("ichimura_3.csv",header=TRUE)
ichimura_4=read.csv("ichimura_4.csv",header=TRUE)
ichimura_5=read.csv("ichimura_5.csv",header=TRUE)
ichimura_6=read.csv("ichimura_6.csv",header=TRUE)
#ichimura_7=read.csv("ichimura_3.csv",header=TRUE)
#ichimura_8=read.csv("ichimura_3.csv",header=TRUE)
KS_1=read.csv("KS_1.csv",header=TRUE)
KS_2=read.csv("KS_2.csv",header=TRUE)
KS_3=read.csv("KS_3.csv",header=TRUE)
KS_4=read.csv("KS_4.csv",header=TRUE)
KS_5=read.csv("KS_5.csv",header=TRUE)
KS_6=read.csv("KS_6.csv",header=TRUE)
#KS_7=read.csv("KS_3.csv",header=TRUE)
#KS_8=read.csv("KS_3.csv",header=TRUE)

#########################################################################
par(mfrow=c(2,6))
hist(ichimura_1$x,breaks = 50, main="ichimura_1")
hist(ichimura_2$x,breaks = 50, main="ichimura_2")
hist(ichimura_3$x,breaks = 50, main="ichimura_3")
hist(ichimura_4$x,breaks = 50, main="ichimura_4")
hist(ichimura_5$x,breaks = 50, main="ichimura_5")
hist(ichimura_6$x,breaks = 50, main="ichimura_6")
#hist(ichimura_7$x,breaks = 50, main="ichimura_7")
#hist(ichimura_8$x,breaks = 50, main="ichimura_8")

hist(KS_1$x,breaks = 50, main="KS_1")
hist(KS_2$x,breaks = 50, main="KS_2")
hist(KS_3$x,breaks = 50, main="KS_3")
hist(KS_4$x,breaks = 50, main="KS_4")
hist(KS_5$x,breaks = 50, main="KS_5")
hist(KS_6$x,breaks = 50, main="KS_6")
#hist(KS_7$x,breaks = 50, main="KS_7")
#hist(KS_8$x,breaks = 50, main="KS_8")


MSE=read.csv("loss_beta.csv")