#! python

def build(ctx):
    # Illustrate use of run_py_script with automatic model specification.
    ctx(
        features='run_py_script',
        source='data_trim_test.py',
        deps='data_trim.py'
    )
    
    # Loop over the models.
    for model in '1','2','3','4':
    
	    ctx(
	        features='run_py_script',
	        source='get_simulation_draws.py',
	        target=[
                 ctx.path_to(ctx, 'OUT_DATA', "x_model_{}.pickle".format(model)),
                 ctx.path_to(ctx, 'OUT_DATA', "y_model_{}.pickle".format(model))
                 ],
	        deps=[
	                ctx.path_to(ctx, 'IN_MODEL_SPECS', 'model_{}.json'.format(model)),
	                'data_trim.py'
	            ],
          append=model,
	        name='get_simulation_draws_{}'.format(model)
	    )
