#! python


def build(ctx):
    # Illustrate use of run_py_script with automatic model specification.

      ctx(
          features='run_py_script',
          source='empirical.py',
          deps=[
             ctx.path_to(ctx, 'IN_EMPIRICAL', "voice.csv"),
             ctx.path_to(ctx, 'ANALYSIS', 'ichimura.py'),
             ctx.path_to(ctx, 'ANALYSIS', 'KS.py')
          ],
          target=[
              ctx.path_to(ctx, 'OUT_EMPIRICAL', 'empirical.pickle')
          ],
          name='empirical'
      )